package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/FYFran/ironwall/internal/agent"
	"github.com/FYFran/ironwall/internal/config"
)

// WriteAgentReport generates an agent-style security report from ScanResult.
//
// This is a bridge between the traditional 8-step pipeline output and the
// AI Agent Engine (Day 5-6). Until the full Agent pipeline is built, this
// produces structured 6/4/1-section reports from existing scanner findings.
//
// Each finding is converted to a minimal AnalystResult with:
//   - Severity-based section template (CRITICAL→6, HIGH→4, MEDIUM→1)
//   - Scanner evidence as EvidenceItem(s)
//   - All findings marked unverified (no AI verification yet)
func WriteAgentReport(result *ScanResult, cfg *config.Config) error {
	builder := agent.NewReportBuilder()

	var buf strings.Builder

	// Header
	buf.WriteString("# 🔍 Ironwall Security Audit — Agent Report\n\n")
	buf.WriteString(fmt.Sprintf("**Target:** %s  \n", result.Target))
	buf.WriteString(fmt.Sprintf("**Version:** %s  \n", result.Version))
	buf.WriteString(fmt.Sprintf("**Started:** %s  \n", result.StartedAt))
	buf.WriteString(fmt.Sprintf("**Duration:** %s  \n", result.Duration))
	buf.WriteString(fmt.Sprintf("**Findings:** %d total (%d CRITICAL, %d HIGH, %d MEDIUM, %d LOW, %d INFO)\n\n",
		result.Summary.Total, result.Summary.Critical, result.Summary.High,
		result.Summary.Medium, result.Summary.Low, result.Summary.Info))

	buf.WriteString("---\n\n")

	// Sort findings: CRITICAL first, then HIGH, then MEDIUM, then rest.
	sorted := sortBySeverity(result.Findings)
	if len(sorted) == 0 {
		buf.WriteString("✅ **No vulnerabilities found.** The scan completed without detecting any issues.\n")
		return writeOutput(buf.String(), cfg)
	}

	// Group and render.
	criticalCount := 0
	for _, f := range sorted {
		if f.Severity == SevCritical {
			criticalCount++
		}
	}

	if criticalCount > 0 {
		buf.WriteString(fmt.Sprintf("## 🚨 CRITICAL Findings (%d)\n\n", criticalCount))
		buf.WriteString("> ⚠️ **IMMEDIATE ACTION REQUIRED.** These vulnerabilities represent active, exploitable risks.\n\n")
	}

	currentSeverity := SevCritical
	for _, f := range sorted {
		// Add severity section headers.
		if f.Severity != currentSeverity {
			currentSeverity = f.Severity
			switch currentSeverity {
			case SevHigh:
				buf.WriteString(fmt.Sprintf("\n## ⚠️ HIGH Severity Findings\n\n"))
			case SevMedium:
				buf.WriteString(fmt.Sprintf("\n## ⚡ MEDIUM Severity Findings\n\n"))
			default:
				buf.WriteString(fmt.Sprintf("\n## ℹ️ %s Severity Findings\n\n", f.Severity))
			}
		}

		// Convert Finding → AnalystResult.
		ar := findingToAgentResult(f)
		report, err := builder.BuildReport(ar)
		if err != nil {
			// Fallback: simple output if report builder fails.
			buf.WriteString(fmt.Sprintf("### %s\n\n", f.Title))
			buf.WriteString(fmt.Sprintf("%s\n\n", f.Description))
			buf.WriteString(fmt.Sprintf("**Location:** `%s:%d`\n\n", f.FilePath, f.LineNumber))
			if f.FixSuggestion != "" {
				buf.WriteString(fmt.Sprintf("**Fix:** %s\n\n", f.FixSuggestion))
			}
			buf.WriteString("---\n\n")
			continue
		}
		buf.WriteString(report)
		buf.WriteString("\n---\n\n")
	}

	// Footer with pipeline summary.
	buf.WriteString("## 📊 Pipeline Summary\n\n")
	buf.WriteString("| Step | Status |\n")
	buf.WriteString("|------|--------|\n")
	for step := 1; step <= 8; step++ {
		name := config.StepNames[step]
		status := "✅ Run"
		for _, s := range result.SkippedSteps {
			if strings.Contains(s, name) {
				status = "⏭️ Skipped"
				break
			}
		}
		buf.WriteString(fmt.Sprintf("| %d. %s | %s |\n", step, name, status))
	}

	buf.WriteString("\n---\n\n")
	buf.WriteString(fmt.Sprintf("*Agent Report generated by Ironwall v%s at %s*\n", result.Version, time.Now().Format(time.RFC3339)))
	buf.WriteString("*Note: Findings are from traditional scanner pipeline. AI-powered analysis (OBSERVE→TRACE→VERIFY→ASSESS) coming in v0.5.0.*\n")

	return writeOutput(buf.String(), cfg)
}

// severityToAgent converts report.Severity (int) to agent.Severity (string).
func severityToAgent(s Severity) agent.Severity {
	switch s {
	case SevCritical:
		return agent.SevCritical
	case SevHigh:
		return agent.SevHigh
	case SevMedium:
		return agent.SevMedium
	case SevLow:
		return agent.SevLow
	default:
		return agent.SevInfo
	}
}

// severityToString converts report.Severity to a display string.
func severityToString(s Severity) string {
	switch s {
	case SevCritical:
		return "CRITICAL"
	case SevHigh:
		return "HIGH"
	case SevMedium:
		return "MEDIUM"
	case SevLow:
		return "LOW"
	default:
		return "INFO"
	}
}

// findingToAgentResult converts a scanner Finding to an AnalystResult
// suitable for the ReportBuilder. This is a bridge — when the full Agent
// Engine is built (Day 5-6), AnalystResult will come from analyst.go instead.
func findingToAgentResult(f Finding) agent.AnalystResult {
	severity := severityToAgent(f.Severity)
	evidence := []agent.EvidenceItem{
		{
			Type:        "scanner",
			Description: f.Description,
			FilePath:    f.FilePath,
			LineNumber:  f.LineNumber,
			CodeSnippet: f.CodeSnippet,
			Confidence:  "likely", // Scanner confidence — AI will refine.
		},
	}

	// If AI was used, upgrade confidence.
	if f.AIConfidence > 0 {
		evidence[0].Confidence = "certain"
	}

	attackPath := []agent.AttackStep{}
	if f.AttackScenario != nil {
		attackPath = buildAttackPathFromScenario(f)
	}

	verification := agent.VerificationResult{
		Verified: f.AIConfidence > 0,
		Method:   "scanner-only",
		Detail:   "Finding from traditional scanner pipeline. AI Agent verification not yet applied (coming Day 7).",
	}

	return agent.AnalystResult{
		FindingID:     f.ID,
		Title:         f.Title,
		Severity:      severity,
		IsExploitable: f.Severity <= SevHigh, // CRITICAL(0) and HIGH(1) assumed exploitable until AI verified.
		Confidence:    f.AIConfidence,
		Narrative:     buildScannerNarrative(f),
		AttackPath:    attackPath,
		Evidence:      evidence,
		Verification:  verification,
		CWE:           f.CWE,
		CVSS:          f.CVSS,
		FixSuggestion: f.FixSuggestion,
		References:    f.References,
		RawFindings: []agent.RawFinding{
			{
				Source:   fmt.Sprintf("step-%d", f.Step),
				RuleID:   f.Category,
				FilePath: f.FilePath,
				Line:     f.LineNumber,
				Snippet:  truncateSnippet(f.CodeSnippet, 100),
			},
		},
	}
}

// buildScannerNarrative creates a basic narrative from scanner finding data.
func buildScannerNarrative(f Finding) string {
	severityLabel := strings.ToLower(severityToString(f.Severity))
	noun := "vulnerability"
	switch f.Category {
	case "hardcoded-secret", "secret-detected":
		noun = "hardcoded secret"
	case "sql-injection":
		noun = "SQL injection vulnerability"
	case "command-injection":
		noun = "command injection vulnerability"
	case "weak-crypto":
		noun = "weak cryptographic usage"
	case "insecure-configuration":
		noun = "insecure configuration"
	}

	return fmt.Sprintf(
		"The scanner detected a %s severity %s in `%s:%d`. "+
			"This finding was identified by step %d (%s) of the Ironwall pipeline. "+
			"AI-powered analysis (attack path construction, evidence verification, "+
			"exploitability assessment) will be applied when the Agent Engine is fully integrated.",
		severityLabel, noun, filepath.Base(f.FilePath), f.LineNumber,
		f.Step, config.StepNames[f.Step],
	)
}

// buildAttackPathFromScenario converts AttackScenario to AttackSteps.
func buildAttackPathFromScenario(f Finding) []agent.AttackStep {
	at := f.AttackScenario
	steps := []agent.AttackStep{}

	if at.Actor != "" {
		steps = append(steps, agent.AttackStep{
			StepNumber:  1,
			Description: fmt.Sprintf("Attacker profile: %s", at.Actor),
			FileRef:     filepath.Base(f.FilePath),
			LineRef:     f.LineNumber,
		})
	}
	if at.Path != "" {
		steps = append(steps, agent.AttackStep{
			StepNumber:  2,
			Description: fmt.Sprintf("Attack path: %s", at.Path),
		})
	}
	if at.Impact != "" {
		steps = append(steps, agent.AttackStep{
			StepNumber:  3,
			Description: fmt.Sprintf("Business impact: %s", at.Impact),
		})
	}
	return steps
}

// sortBySeverity sorts findings by severity (CRITICAL first).
func sortBySeverity(findings []Finding) []Finding {
	order := map[Severity]int{
		SevCritical: 0,
		SevHigh:     1,
		SevMedium:   2,
		SevLow:      3,
		SevInfo:     4,
	}

	sorted := make([]Finding, len(findings))
	copy(sorted, findings)

	// Simple bubble sort — N is small (<100 findings typically).
	for i := 0; i < len(sorted); i++ {
		for j := i + 1; j < len(sorted); j++ {
			if order[sorted[i].Severity] > order[sorted[j].Severity] {
				sorted[i], sorted[j] = sorted[j], sorted[i]
			}
		}
	}
	return sorted
}

// truncateSnippet truncates a code snippet to maxLen characters.
func truncateSnippet(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// writeOutput writes the report to stdout and optionally to a file.
func writeOutput(content string, cfg *config.Config) error {
	fmt.Fprint(os.Stdout, content)

	if cfg.OutputFile != "" {
		if err := os.WriteFile(cfg.OutputFile, []byte(content), 0644); err != nil {
			return fmt.Errorf("write output file: %w", err)
		}
		fmt.Fprintf(os.Stderr, "\nReport saved to: %s\n", cfg.OutputFile)
	}
	return nil
}
