package report

import (
	"fmt"
	"html"
	"os"
	"strings"

	"github.com/FYFran/ironwall/internal/config"
)

// WriteHTML generates a self-contained HTML report.
// All user data (code snippets, file paths) is HTML-escaped to prevent XSS.
func WriteHTML(result *ScanResult, cfg *config.Config) error {
	filename := cfg.ReportFilename()
	filename = strings.TrimSuffix(filename, ".md")
	filename = strings.TrimSuffix(filename, ".json")
	filename += ".html"

	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create HTML report: %w", err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	// ── Header ──
	w(`<!DOCTYPE html>`)
	w(`<html lang="zh-CN">`)
	w(`<head>`)
	w(`<meta charset="UTF-8">`)
	w(`<meta name="viewport" content="width=device-width, initial-scale=1.0">`)
	w(`<title>Ironwall Security Audit — %s</title>`, html.EscapeString(result.Target))
	w(`<style>`)
	w(cssStyles)
	w(`</style>`)
	w(`</head>`)
	w(`<body>`)
	w(`<div class="container">`)

	// ── Header bar ──
	w(`<header>`)
	w(`<h1>🛡️ Ironwall Security Audit</h1>`)
	w(`<div class="meta">`)
	w(`<span>📁 %s</span>`, html.EscapeString(result.Target))
	w(`<span>⏱️ %s</span>`, html.EscapeString(result.Duration))
	w(`<span>📅 %s</span>`, html.EscapeString(result.CompletedAt))
	w(`<span>v%s</span>`, html.EscapeString(result.Version))
	w(`</div>`)
	w(`</header>`)

	// ── Summary cards ──
	s := result.Summary
	w(`<section class="summary">`)
	summaryCard(w, "🔴 Critical", s.Critical, "#dc2626")
	summaryCard(w, "🟠 High", s.High, "#ea580c")
	summaryCard(w, "🟡 Medium", s.Medium, "#ca8a04")
	summaryCard(w, "🟢 Low", s.Low, "#16a34a")
	summaryCard(w, "ℹ️ Info", s.Info, "#6b7280")
	summaryCard(w, "📊 Total", s.Total, "#4f46e5")
	w(`</section>`)

	// AI status
	aiLabel := result.AnalysisStatus
	if aiLabel == "full" {
		aiLabel = "✅ AI analysis complete"
	} else if aiLabel == "partial" {
		aiLabel = "⚠️ AI analysis partial"
	} else if aiLabel == "skipped" {
		aiLabel = "⏭️ AI analysis skipped"
	} else {
		aiLabel = "❌ AI analysis error"
	}
	w(`<div class="ai-status">%s</div>`, html.EscapeString(aiLabel))

	// ── Filter bar ──
	w(`<section class="filters">`)
	w(`<input type="text" id="search" placeholder="🔍 Search findings..." oninput="filterFindings()">`)
	w(`<select id="sevFilter" onchange="filterFindings()">`)
	w(`<option value="all">All Severities</option>`)
	w(`<option value="CRITICAL">🔴 Critical</option>`)
	w(`<option value="HIGH">🟠 High</option>`)
	w(`<option value="MEDIUM">🟡 Medium</option>`)
	w(`<option value="LOW">🟢 Low</option>`)
	w(`<option value="INFO">ℹ️ Info</option>`)
	w(`</select>`)
	w(`<select id="cweFilter" onchange="filterFindings()">`)
	w(`<option value="all">All CWEs</option>`)
	for _, cwe := range uniqueCWEs(result.Findings) {
		w(`<option value="%s">%s</option>`, html.EscapeString(cwe), html.EscapeString(cwe))
	}
	w(`</select>`)
	w(`<span id="filterCount" class="filter-count"></span>`)
	w(`</section>`)

	// ── Findings ──
	w(`<section class="findings" id="findings">`)
	for i, f := range result.Findings {
		renderFinding(w, i, f)
	}
	w(`</section>`)

	// ── Footer ──
	w(`<footer>`)
	w(`<p>Generated by <strong>Ironwall</strong> — AI-powered offline code security audit</p>`)
	w(`<p>⚠️ Findings require human review. Not all detected issues are exploitable.</p>`)
	w(`</footer>`)

	w(`</div>`)

	// ── Scripts ──
	w(`<script>`)
	w(filterScript)
	w(`</script>`)
	w(`</body>`)
	w(`</html>`)

	fmt.Printf("  📄 HTML report saved: %s\n", filename)
	return nil
}

func summaryCard(w func(string, ...interface{}), label string, count int, color string) {
	w(`<div class="card" style="border-left: 4px solid %s">`, color)
	w(`<div class="card-label">%s</div>`, label)
	w(`<div class="card-count">%d</div>`, count)
	w(`</div>`)
}

func renderFinding(w func(string, ...interface{}), idx int, f Finding) {
	sevClass := strings.ToLower(f.Severity.String())
	cwe := f.CWE
	if cwe == "" {
		cwe = "N/A"
	}

	w(`<div class="finding" data-severity="%s" data-cwe="%s" data-id="%s">`,
		html.EscapeString(f.Severity.String()), html.EscapeString(cwe), html.EscapeString(f.ID))

	// Header row
	w(`<div class="finding-header" onclick="this.parentElement.classList.toggle('expanded')">`)
	w(`<span class="sev sev-%s">%s</span>`, sevClass, html.EscapeString(f.Severity.String()))
	w(`<span class="finding-title">%s</span>`, html.EscapeString(f.Title))
	w(`<span class="finding-loc">%s:%d</span>`, html.EscapeString(f.FilePath), f.LineNumber)
	w(`<span class="expand-icon">▼</span>`)
	w(`</div>`)

	// Detail body
	w(`<div class="finding-body">`)

	// Meta grid
	w(`<div class="meta-grid">`)
	metaItem(w, "CWE", cwe)
	metaItem(w, "Category", f.Category)
	metaItem(w, "AI Confidence", fmt.Sprintf("%.0f%%", f.AIConfidence*100))
	metaItem(w, "CVSS", fmt.Sprintf("%.1f", f.CVSS))
	w(`</div>`)

	// Description
	if f.Description != "" {
		w(`<div class="section">`)
		w(`<h3>📝 Description</h3>`)
		w(`<p>%s</p>`, html.EscapeString(f.Description))
		w(`</div>`)
	}

	// Code snippet (XSS SAFE: use textContent via <pre><code>)
	if f.CodeSnippet != "" {
		w(`<div class="section">`)
		w(`<h3>💻 Code</h3>`)
		w(`<pre class="code-block"><code>%s</code></pre>`, html.EscapeString(f.CodeSnippet))
		w(`</div>`)
	}

	// AI Attack Scenario
	if f.AttackScenario != nil {
		w(`<div class="section ai-box">`)
		w(`<h3>🎯 AI Attack Analysis (confidence: %.0f%%)</h3>`, f.AIConfidence*100)
		if f.AttackScenario.IsReal {
			w(`<div class="ai-verdict real">⚠️ Attack scenario is VIABLE</div>`)
		} else {
			w(`<div class="ai-verdict safe">✅ Attack scenario NOT viable</div>`)
		}
		if f.AttackScenario.Actor != "" {
			w(`<h4>👤 Attacker</h4>`)
			w(`<p>%s</p>`, html.EscapeString(f.AttackScenario.Actor))
		}
		if f.AttackScenario.Path != "" {
			w(`<h4>🔗 Attack Path</h4>`)
			w(`<p>%s</p>`, html.EscapeString(f.AttackScenario.Path))
		}
		if f.AttackScenario.Impact != "" {
			w(`<h4>💥 Impact</h4>`)
			w(`<p>%s</p>`, html.EscapeString(f.AttackScenario.Impact))
		}
		if f.AttackScenario.Explanation != "" {
			w(`<h4>📋 Reasoning</h4>`)
			w(`<p>%s</p>`, html.EscapeString(f.AttackScenario.Explanation))
		}
		w(`</div>`)
	}

	// Fix suggestion
	if f.FixSuggestion != "" {
		w(`<div class="section">`)
		w(`<h3>🔧 Fix</h3>`)
		w(`<p>%s</p>`, html.EscapeString(f.FixSuggestion))
		w(`</div>`)
	}

	w(`</div>`) // finding-body
	w(`</div>`) // finding
}

func metaItem(w func(string, ...interface{}), label, value string) {
	w(`<div class="meta-item"><strong>%s</strong><br>%s</div>`, html.EscapeString(label), html.EscapeString(value))
}

func uniqueCWEs(findings []Finding) []string {
	seen := map[string]bool{}
	var result []string
	for _, f := range findings {
		cwe := f.CWE
		if cwe == "" {
			cwe = "N/A"
		}
		if !seen[cwe] {
			seen[cwe] = true
			result = append(result, cwe)
		}
	}
	return result
}

// ── CSS (inline, no external deps) ──

const cssStyles = `
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
.container { max-width: 1200px; margin: 0 auto; padding: 20px; }

header { background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 24px; border: 1px solid #334155; }
header h1 { font-size: 24px; margin-bottom: 8px; }
header .meta { display: flex; gap: 20px; font-size: 13px; color: #94a3b8; flex-wrap: wrap; }

.summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 16px; }
.card { background: #1e293b; border-radius: 8px; padding: 16px; border: 1px solid #334155; }
.card-label { font-size: 12px; color: #94a3b8; margin-bottom: 4px; }
.card-count { font-size: 28px; font-weight: 700; }

.ai-status { text-align: center; padding: 8px; margin-bottom: 16px; font-size: 13px; color: #94a3b8; background: #1e293b; border-radius: 8px; border: 1px solid #334155; }

.filters { display: flex; gap: 12px; margin-bottom: 20px; flex-wrap: wrap; align-items: center; }
.filters input, .filters select { background: #1e293b; border: 1px solid #475569; color: #e2e8f0; padding: 8px 12px; border-radius: 6px; font-size: 14px; }
.filters input { flex: 1; min-width: 200px; }
.filters input:focus, .filters select:focus { outline: none; border-color: #4f46e5; }
.filter-count { font-size: 13px; color: #94a3b8; }

.finding { background: #1e293b; border-radius: 8px; margin-bottom: 8px; border: 1px solid #334155; overflow: hidden; }
.finding-header { display: flex; align-items: center; gap: 12px; padding: 12px 16px; cursor: pointer; user-select: none; }
.finding-header:hover { background: #263348; }
.finding-title { flex: 1; font-size: 14px; font-weight: 500; }
.finding-loc { font-size: 12px; color: #94a3b8; font-family: monospace; }
.expand-icon { font-size: 10px; color: #64748b; transition: transform 0.2s; }
.finding.expanded .expand-icon { transform: rotate(180deg); }

.sev { font-size: 11px; font-weight: 700; padding: 2px 8px; border-radius: 4px; text-transform: uppercase; white-space: nowrap; }
.sev-critical { background: #7f1d1d; color: #fca5a5; }
.sev-high { background: #7c2d12; color: #fdba74; }
.sev-medium { background: #713f12; color: #fde047; }
.sev-low { background: #14532d; color: #86efac; }
.sev-info { background: #334155; color: #94a3b8; }

.finding-body { display: none; padding: 0 16px 16px; }
.finding.expanded .finding-body { display: block; }

.meta-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 8px; margin-bottom: 12px; }
.meta-item { background: #0f172a; padding: 8px 12px; border-radius: 6px; font-size: 13px; }
.meta-item strong { color: #94a3b8; font-size: 11px; }

.section { margin-bottom: 12px; }
.section h3 { font-size: 14px; margin-bottom: 6px; color: #cbd5e1; }
.section h4 { font-size: 13px; margin: 8px 0 4px; color: #94a3b8; }
.section p { font-size: 13px; color: #cbd5e1; }

.code-block { background: #0f172a; border: 1px solid #334155; border-radius: 6px; padding: 12px; overflow-x: auto; font-size: 12px; line-height: 1.5; font-family: 'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace; }
.code-block code { color: #e2e8f0; }

.ai-box { background: #1a1a2e; border: 1px solid #4f46e5; border-radius: 8px; padding: 12px; }
.ai-verdict { font-size: 13px; font-weight: 600; padding: 6px 12px; border-radius: 6px; margin-bottom: 8px; }
.ai-verdict.real { background: #7f1d1d; color: #fca5a5; }
.ai-verdict.safe { background: #14532d; color: #86efac; }

footer { text-align: center; padding: 24px; color: #64748b; font-size: 12px; border-top: 1px solid #334155; margin-top: 24px; }

@media (max-width: 640px) {
  .summary { grid-template-columns: repeat(3, 1fr); }
  .finding-header { flex-wrap: wrap; }
}
`

// ── JS (inline, no external deps) ──

const filterScript = `
function filterFindings() {
  var search = (document.getElementById('search').value || '').toLowerCase();
  var sev = document.getElementById('sevFilter').value;
  var cwe = document.getElementById('cweFilter').value;
  var findings = document.querySelectorAll('.finding');
  var visible = 0;
  findings.forEach(function(f) {
    var title = (f.querySelector('.finding-title').textContent || '').toLowerCase();
    var desc = (f.querySelector('.finding-body').textContent || '').toLowerCase();
    var fsev = f.dataset.severity;
    var fcwe = f.dataset.cwe;
    var match = (sev === 'all' || fsev === sev) &&
                (cwe === 'all' || fcwe === cwe) &&
                (search === '' || title.indexOf(search) >= 0 || desc.indexOf(search) >= 0);
    f.style.display = match ? '' : 'none';
    if (match) visible++;
  });
  document.getElementById('filterCount').textContent = visible + ' / ' + findings.length + ' findings';
}
// Initial count
window.addEventListener('DOMContentLoaded', function() {
  document.getElementById('filterCount').textContent = document.querySelectorAll('.finding').length + ' findings';
});
`
