package report

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/FYFran/ironwall/internal/config"
)

// WriteMarkdown generates a markdown report and writes it to a file.
func WriteMarkdown(result *ScanResult, cfg *config.Config) error {
	filename := cfg.ReportFilename()
	f, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("failed to create report file: %w", err)
	}
	defer f.Close()

	w := &mdWriter{f: f}
	w.w("# 🔍 Ironwall Security Audit Report\n\n")
	w.w("**Target:** `%s`  \n", result.Target)
	w.w("**Date:** %s  \n", time.Now().Format("2006-01-02 15:04:05"))
	w.w("**Duration:** %s  \n", result.Duration)
	w.w("**Tool Version:** ironwall v%s  \n\n", result.Version)

	// Summary table
	w.w("## 📊 Summary\n\n")
	w.w("| Severity | Count |\n")
	w.w("|----------|-------|\n")
	w.w("| 🔴 CRITICAL | %d |\n", result.Summary.Critical)
	w.w("| 🟠 HIGH | %d |\n", result.Summary.High)
	w.w("| 🟡 MEDIUM | %d |\n", result.Summary.Medium)
	w.w("| 🟢 LOW | %d |\n", result.Summary.Low)
	w.w("| ℹ️ INFO | %d |\n", result.Summary.Info)
	w.w("| **Total** | **%d** |\n\n", result.Summary.Total)

	// Skipped steps
	if len(result.SkippedSteps) > 0 {
		w.w("## ⚠️ Skipped Steps\n\n")
		for _, s := range result.SkippedSteps {
			w.w("- %s\n", s)
		}
		w.w("\n")
	}

	// Findings by severity
	severityOrder := []Severity{SevCritical, SevHigh, SevMedium, SevLow, SevInfo}
	severityGroups := groupBySeverity(result.Findings)

	for _, sev := range severityOrder {
		findings, ok := severityGroups[sev]
		if !ok || len(findings) == 0 {
			continue
		}

		w.w("## %s %s Findings\n\n", sev.Emoji(), sev.String())

		for _, f := range findings {
			writeMarkdownFinding(w, f)
		}
	}

	// Footer
	w.w("\n---\n\n")
	w.w("*Report generated by [Ironwall v%s](https://github.com/FYFran/ironwall) — 8-Step Security Audit CLI*\n", result.Version)

	fmt.Printf("  📄 Report saved: %s\n", filename)
	return nil
}

// mdWriter is a tiny helper for writing formatted lines to a markdown file.
type mdWriter struct {
	f *os.File
}

func (w *mdWriter) w(format string, args ...interface{}) {
	fmt.Fprintf(w.f, format, args...)
}

// writeMarkdownFinding writes a single finding in full detail.
func writeMarkdownFinding(w *mdWriter, f Finding) {
	w.w("### %s: %s\n\n", f.ID, f.Title)
	w.w("**File:** `%s:%d`  \n", f.FilePath, f.LineNumber)
	w.w("**Category:** %s  \n", f.Category)
	if f.CWE != "" {
		w.w("**CWE:** %s  \n", f.CWE)
	}
	if f.CVSS > 0 {
		w.w("**CVSS:** %.1f  \n", f.CVSS)
	}
	if f.AIConfidence > 0 {
		w.w("**AI Confidence:** %.0f%%  \n", f.AIConfidence*100)
	}
	w.w("\n")

	if f.CodeSnippet != "" {
		w.w("**Code:**\n```\n%s\n```\n\n", strings.TrimSpace(f.CodeSnippet))
	}

	if f.AttackScenario != nil && f.AttackScenario.IsReal {
		w.w("**Attack Scenario:**\n")
		w.w("- **Actor:** %s\n", f.AttackScenario.Actor)
		w.w("- **Path:** %s\n", f.AttackScenario.Path)
		w.w("- **Impact:** %s\n\n", f.AttackScenario.Impact)
	}

	if f.FixSuggestion != "" {
		w.w("**Fix:**\n%s\n\n", f.FixSuggestion)
	}

	if len(f.References) > 0 {
		w.w("**References:**\n")
		for _, ref := range f.References {
			w.w("- %s\n", ref)
		}
		w.w("\n")
	}

	w.w("---\n\n")
}

// groupBySeverity groups findings by severity level.
func groupBySeverity(findings []Finding) map[Severity][]Finding {
	m := make(map[Severity][]Finding)
	for _, f := range findings {
		m[f.Severity] = append(m[f.Severity], f)
	}
	return m
}

// WriteJSON generates a JSON report and writes it to a file.
func WriteJSON(result *ScanResult, cfg *config.Config) error {
	filename := cfg.ReportFilename()
	if !strings.HasSuffix(filename, ".json") {
		filename = strings.TrimSuffix(filename, ".md") + ".json"
	}

	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal JSON: %w", err)
	}

	if err := os.WriteFile(filename, data, 0644); err != nil {
		return fmt.Errorf("failed to write JSON report: %w", err)
	}

	fmt.Printf("  📄 JSON report saved: %s\n", filename)
	return nil
}

func escapeJSON(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return s
}
